[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "unslam"
version = "0.1.0"
description = "Filter topics and TF frames from a rosbag."
requires-python = ">=3.10"
dependencies = [
    "rosbags",
    "tqdm",
]

[project.scripts]
unslam = "unslam.__main__:main"

[tool.setuptools.packages.find]
include = ["unslam*"]
